---
title: "PrepCAISOData"
author: "James Woods"
date: "12/15/2014"
output: html_document
---

Read in the data from the CAISO

```{r}
OldWD<-getwd()
setwd("/home/woodsj/Research/Forecast-Peak-With-Google-Trends/CAData/CAISO")
# Get the files names
files <- list.files(pattern="*.csv")

# First apply read.csv, then rbind
CAISORaw<- do.call("rbind", lapply(files, function(x) read.csv(x, stringsAsFactors = FALSE)))

```
Editing of data types.  Remember that most everything gets imported as a string.

```{r}

CAISORaw$MARKET_RUN_ID<-as.factor(CAISORaw$MARKET_RUN_ID)
CAISORaw$TAC_AREA_NAME<-as.factor(CAISORaw$TAC_AREA_NAME)
CAISORaw$StartTimeGMT<-as.POSIXct(CAISORaw$INTERVALSTARTTIME_GMT)
```
Now trim off all but the full ISO area

```{r}
CAISOWorking<-CAISORaw[CAISORaw$TAC_AREA_NAME=='CA ISO-TAC',]
save(CAISOWorking,file="CAISOWorking.Rdata")
```

Now lets sort out how the 7day ahead market is related to the actual

```{r}

CAISOWorking$Hour<-as.factor(CAISOWorking$OPR_HR)
#line up actual and 7day with the time in the line

Forecast<-CAISOWorking[CAISOWorking$MARKET_RUN_ID=="7DA",]
Actual<-CAISOWorking[CAISOWorking$MARKET_RUN_ID=="ACTUAL",]

library(sqldf)
sqldf("select * from Actual;")

sqldf("select Actual.Hour, Actual.OPR_DT, Actual.MW as Actual, Forecast.MW as Forecast from Forecast, Actual where Actual.Hour=Forecast.Hour and Actual.OPR_DT=Forecast.OPR_DT;")

table(CAISOWorking$INTERVALSTARTTIME_GMT)

#line up acutal with 7day from seven days before.

```


