---
title: "DataCleaning"
author: "James Woods"
date: "07/24/2014"
output: html_document
---
Load data is from http://www.pjm.com/markets-and-operations/ops-analysis/historical-load-data.aspx

Forecasts are from 

http://www.pjm.com/markets-and-operations/ops-analysis/historical-load-forecasts.aspx


Load in the Trends data.
```{r}
# Data is from
Load data is from http://www.pjm.com/markets-and-operations/ops-analysis/historical-load-data.aspx

Forecasts are from 

http://www.pjm.com/markets-and-operations/ops-analysis/historical-load-forecasts.aspx

library(stringr)
ReadTrends<-function(fileName){
  path<-paste("~/Research/Forecast-Peak-With-Google-Trends/TrendsData/",fileName,sep='')
  file<-read.csv(path)
  names(file)<-c("Date",str_sub(fileName,1, str_length(fileName)-4))
  as.POSIXct(file$Date)
  file
}

#Get the names of the trend files
TrendsFiles<-list.files("~/Research/Forecast-Peak-With-Google-Trends/TrendsData", pattern="*.W.csv",all.files= FALSE)


#all the trends in one data frame
AllTrends<-as.data.frame(lapply(TrendsFiles,FUN=ReadTrends))

#Kill the "Date.*" columnns that are duplicates of Date.  Assuming here that the dates all line up
JustTrends<-AllTrends[,c(1,2,seq(from=4,to=length(names(AllTrends)),by=2))]

#Cleanup
rm(AllTrends,TrendsFiles)

#Just in case we want this alone
save(JustTrends,file="JustTrends")
```

On to the forecast data.
```{r}

Loads<- read.csv("~/Research/Forecast-Peak-With-Google-Trends/LoadAndForecastData/2014-hourly-loads.csv",header = TRUE)

Forecasts <- read.csv("~/Research/Forecast-Peak-With-Google-Trends/LoadAndForecastData/2014-rto-forecasts.csv",header = TRUE)
```


There are a few columns we don't need so trim and we need some dates in ISO format
```{r}
Loads<-Loads[,1:26]

# Date manipulation

Loads$Date<-as.POSIXct(Loads$DATE, format="%m/%d/%Y")
Forecasts$ForecastDate<-as.POSIXct(Forecasts$Effective., format="%m/%d/%Y")  

#There are several forecasts in a day.  Use only the early one  5am
Forecasts<-Forecasts[as.POSIXlt(Forecasts$Evaluated.at.,format="%m/%d/%Y %H:%M:%S" )$hour==5,]

#Fix the date forecast was made on
Forecasts$Forecasted<-as.POSIXct(Forecasts$Evaluated.at.,format="%m/%d/%Y")


#Make sure we only have day ahead forecasts
table(Forecasts$Forecasted-Forecasts$ForecastDate)
Forecasts<-Forecasts[Forecasts$Forecasted-Forecasts$ForecastDate<(-82800) ,]


```

Time to join the two tables.  The key will be to link them by the trends data from the day before the forecast.  

```{r}
#Link forecasts to actual.

#need to kill a few columns with . in the name
Forecasts$Evaluated.at.<-NULL
Forecasts$Effective.<-NULL
names(Forecasts)[1:24]<-c("F01","F02","F03","F04","F05","F06","F07","F08","F09","F10","F11","F12","F13","F14","F15","F16","F17","F18","F19","F20","F21","F22","F23","F24")
Forecasts$Date<-Forecasts$ForecastDate

library(plyr)
RTO<-join(Forecasts, Loads, by="Date")

#clean up
rm(Forecasts,Loads)

#
JustTrends$TrendDate<-JustTrends$Date
JustTrends$Date<-as.POSIXct(JustTrends$Date)+2*60*24*60

WTrends<-join(RTO,JustTrends, by="Date")
#save for later use
save(WTrends,file="WTrends")

```
Summary
```{r}
summary(WTrends)

```

